#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

shopt -s extglob
# remove initial fields
(
	cd 0/batteryRegion
	rm -f !(orig)
)
(
	cd 0/negTabRegion
	rm -f !(orig)
)
(
	cd 0/posTabRegion
	rm -f !(orig)
)

# remove meshes
(
	cd constant/batteryRegion/polyMesh
	rm -f !(blockMeshDict)

	cd ../faMesh
	rm -f !(faMeshDefinition)
)
(
	cd constant/negTabRegion/polyMesh
	rm -f !(blockMeshDict)

	cd ../faMesh
	rm -f !(faMeshDefinition)
)
(
	cd constant/posTabRegion/polyMesh
	rm -f !(blockMeshDict)

	cd ../faMesh
	rm -f !(faMeshDefinition)
)