#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! $# == 1 ]; then
        echo "Missing options!"
        echo "(run $0 -p for partitioned"
        echo " or -m for monolithic)"
        echo ""
        exit 0
fi

while getopts "pm" OPTION; do
        case $OPTION in

        p)
            cp 0/batteryRegion/orig/partitioned/* 0/batteryRegion/.
            cp 0/negTabRegion/orig/partitioned/* 0/negTabRegion/.
            cp 0/posTabRegion/orig/partitioned/* 0/posTabRegion/.

            runApplication -l log.blockMesh.batteryRegion blockMesh -region batteryRegion 2>/dev/null
            runApplication -l log.makeFaMesh.batteryRegion makeFaMesh -region batteryRegion 2>/dev/null

            runApplication -l log.blockMesh.negTabRegion blockMesh -region negTabRegion 2>/dev/null
            runApplication -l log.makeFaMesh.negTabRegion makeFaMesh -region negTabRegion 2>/dev/null

            runApplication -l log.blockMesh.posTabRegion blockMesh -region posTabRegion 2>/dev/null
            runApplication -l log.makeFaMesh.posTabRegion makeFaMesh -region posTabRegion 2>/dev/null
            ;;

        m)
            echo "Monolithic not supported"
            echo ""
        exit 0
            ;;

        esac
done

runApplication multiRegionFoam 2>/dev/null &