#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

shopt -s extglob
# remove initial fields
(
	cd 0/batteryRegion
	rm -f !(orig)

	cd ../air
	rm T
)

# remove meshes
(
	cd constant/batteryRegion/polyMesh
	rm -f !(blockMeshDict)

	cd ../faMesh
	rm -f !(faMeshDefinition)

    cd ../../air/polyMesh
	rm -f *

	cd ../faMesh
	rm -f !(faMeshDefinition)

	cd ../../triSurface
	rm cell.stl

	cd ../
	rm polyMesh
)