#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

if [ ! $# == 1 ]; then
        echo "Missing options!"
        echo "(run $0 -p for partitioned"
        echo " or -m for monolithic)"
        echo ""
        exit 0
fi

while getopts "pm" OPTION; do
        case $OPTION in

        p)
            cp 0/batteryRegion/orig/partitioned/* 0/batteryRegion/.
            cp 0/air/orig/partitioned/* 0/air/.

            runApplication -l log.blockMesh.batteryRegion blockMesh -region batteryRegion 2>/dev/null
            runApplication -l log.checkMesh.batteryRegion checkMesh -region batteryRegion 2>/dev/null
            runApplication -l log.makeFaMesh.batteryRegion makeFaMesh -region batteryRegion 2>/dev/null
            runApplication -l log.surfaceMeshTriangulate.batteryRegion surfaceMeshTriangulate -region 'batteryRegion' ./constant/triSurface/cell.stl 2>/dev/null
            runApplication -l log.blockMesh.air blockMesh -dict ./system/blockMeshDict 2>/dev/null
            runApplication -l log.snappyHexMesh.air snappyHexMesh -overwrite 2>/dev/null
            mv constant/polyMesh constant/air/.
            mv constant/cellLevel constant/air/.
            mv constant/pointLevel constant/air/.
            runApplication -l log.checkMesh.air checkMesh -region air 2>/dev/null
            runApplication -l log.makeFaMesh.air makeFaMesh -region air 2>/dev/null

            ./makeLinks batteryRegion

            ;;

        m)
            echo "Monolithic not supported"
            echo ""
        exit 0
            ;;

        esac
done

runApplication multiRegionFoam 2>/dev/null