#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

usage() {
        echo ""
        echo "Usage:"
        echo "($0 [-p or --partitioned | -m or --monolithic] [-S or --serial | -P or --parallel]"
        echo ""
        exit 0
}

# $@ is all command line parameters passed to the script.
# -o is for short options like -v
# -l is for long options with double dash like --version
# the comma separates different long options
# -a is for long options with single dash like -version
options=$(getopt -l "help,partitioned,monolithic:,serial,parallel" -o "hpm:SP" -a -- "$@")
# set --:
# If no arguments follow this option, then the positional parameters are unset.
# Otherwise, the positional parameters are set to the arguments, even if some
# of them begin with a ‘-’.
eval set -- "$options"
no_args=1
while true
do
    case $1 in
        -h|--help)
            usage
            exit 0
            ;;

        -p|--partitioned)
            no_args=0

            cp 0/batteryRegion/orig/partitioned/* 0/batteryRegion/.
            cp 0/air/orig/partitioned/* 0/air/.

            runApplication -l log.blockMesh.batteryRegion blockMesh -region batteryRegion 2>/dev/null
            runApplication -l log.checkMesh.batteryRegion checkMesh -region batteryRegion 2>/dev/null
            runApplication -l log.makeFaMesh.batteryRegion makeFaMesh -region batteryRegion 2>/dev/null
            runApplication -l log.surfaceMeshTriangulate.batteryRegion surfaceMeshTriangulate -region 'batteryRegion' ./constant/triSurface/cell.stl 2>/dev/null
            runApplication -l log.blockMesh.air blockMesh -dict ./system/blockMeshDict 2>/dev/null
            runApplication -l log.snappyHexMesh.air snappyHexMesh -overwrite 2>/dev/null
            mv constant/polyMesh constant/air/.
            mv constant/cellLevel constant/air/.
            mv constant/pointLevel constant/air/.
            runApplication -l log.checkMesh.air checkMesh -region air 2>/dev/null
            runApplication -l log.makeFaMesh.air makeFaMesh -region air 2>/dev/null

            ./makeLinks batteryRegion

            ;;

        -m|--monolithic)
            no_args=0
            echo "Monolithic not supported"
            echo ""
        exit 0
            ;;


        -S|--serial)

            no_args=0

            runApplication multiRegionFoam 2>/dev/null

            ;;

        -P|--parallel)

            no_args=0

            runApplication -l log.decomposePar.batteryRegion decomposePar -region batteryRegion
            runApplication -l log.decomposePar.air decomposePar -region air

            mpirun -np 4 multiRegionFoam -noFunctionObjects -parallel 2>&1 > log.multiRegionFoam

            #runApplication -l log.reconstructPar.batteryRegion reconstructPar -region batteryRegion
            #runApplication -l log.reconstructPar.batteryRegion reconstructPar -region air

            #rm -r processor*

            ;;

        --)
            shift
            break;;
    esac
    shift
done

if [ "$no_args" -eq 1 ]; then
    >&2 echo "No arguments provided"
    usage
    exit 1
fi

