#!/bin/sh

. $WM_PROJECT_DIR/bin/tools/CleanFunctions

find -type l -delete

rm -rf 0.* [1-9]* log* proc* VTK

rm constant/amb/polyMesh/blockMeshDict 2>/dev/null
rm constant/cell/polyMesh/blockMeshDict 2>/dev/null

rm 0/amb/T 2>/dev/null
rm 0/amb/k 2>/dev/null

rm 0/cell/T 2>/dev/null
rm 0/cell/k 2>/dev/null
rm 0/cell/faiPos 2>/dev/null
rm 0/cell/faiNeg 2>/dev/null

rm constant/regionInterfaceProperties 2>/dev/null

cleanCase