#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

usage() {
        echo ""
        echo "Usage:"
        echo "($0 [-p or --partitioned | -m or --monolithic] [-S or --serial | -P or --parallel]"
        echo ""
        exit 0
}

# $@ is all command line parameters passed to the script.
# -o is for short options like -v
# -l is for long options with double dash like --version
# the comma separates different long options
# -a is for long options with single dash like -version
options=$(getopt -l "help,partitioned,monolithic:,serial,parallel" -o "hpm:SP" -a -- "$@")

# set --:
# If no arguments follow this option, then the positional parameters are unset.
# Otherwise, the positional parameters are set to the arguments, even if some
# of them begin with a ‘-’.
eval set -- "$options"

no_args=1

while true
do
    case $1 in

        -h|--help)
            usage
            exit 0
            ;;

        -p|--partitioned)
            no_args=0

            cp 0/amb/orig/partitioned/T 0/amb/.
            cp 0/cell/orig/partitioned/T 0/cell/.
            cp 0/cell/orig/partitioned/faiPos 0/cell/.
            cp 0/cell/orig/partitioned/faiNeg 0/cell/.

            cp constant/amb/polyMesh/blockMeshDictPartitioned constant/amb/polyMesh/blockMeshDict 2>/dev/null
            cp constant/cell/polyMesh/blockMeshDictPartitioned constant/cell/polyMesh/blockMeshDict 2>/dev/null

            cp constant/regionInterfacePropertiesPartitioned constant/regionInterfaceProperties

            runApplication -l log.blockMesh.cell blockMesh -region cell 2>/dev/null
            runApplication blockMesh -region amb 2>/dev/null

            runApplication makeFaMesh -region amb 2>/dev/null
            runApplication -l log.makeFaMesh.cell makeFaMesh -region cell 2>/dev/null

            ./makeLinks amb

            ;;

        -m|--monolithic)
            no_args=0

            cp 0/amb/orig/monolithic/T 0/amb/.
            cp 0/amb/orig/monolithic/k 0/amb/.
            cp 0/cell/orig/monolithic/T 0/cell/.
            cp 0/cell/orig/monolithic/k 0/cell/.

            cp constant/amb/polyMesh/blockMeshDictMonolithic constant/amb/polyMesh/blockMeshDict 2>/dev/null
            cp constant/cell/polyMesh/blockMeshDictMonolithic constant/cell/polyMesh/blockMeshDict 2>/dev/null

            cp constant/regionInterfacePropertiesMonolithic constant/regionInterfaceProperties

            runApplication -l log.blockMesh.cell blockMesh -region cell 2>/dev/null
            runApplication -l log.setSet.cell setSet -region cell -batch cell.setSet 2>/dev/null
            runApplication -l log.setsToZones.cell setsToZones -region cell -noFlipMap 2>/dev/null

            runApplication blockMesh -region amb 2>/dev/null
            runApplication setSet -region amb -batch amb.setSet 2>/dev/null
            runApplication setsToZones -region amb -noFlipMap 2>/dev/null

            runApplication makeFaMesh -region amb 2>/dev/null
            runApplication -l log.makeFaMesh.cell makeFaMesh -region cell 2>/dev/null

            ./makeLinks amb

            ;;

        -S|--serial)
            no_args=0

            runApplication multiRegionFoam 2>/dev/null

            ;;

        -P|--parallel)
            no_args=0

            runApplication -l log.decomposePar.amb decomposePar -region amb
            runApplication -l log.decomposePar.cell  decomposePar -region cell

            mpirun -np 4 multiRegionFoam -noFunctionObjects -parallel 2>&1 > log.multiRegionFoam

            runApplication -l log.reconstructPar.amb reconstructPar -region amb
            runApplication -l log.reconstructPar.cell reconstructPar -region cell

            rm -r processor*
            ;;

        --)
            shift
            break;;
    esac
    shift
done

if [ "$no_args" -eq 1 ]; then
    >&2 echo "No arguments provided"
    usage
    exit 1
fi