#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

shopt -s extglob
# remove initial fields
(
	cd 0/batteryRegion
	rm -f !(orig)
)

# remove meshes
(
	cd constant/batteryRegion/polyMesh
	rm -f !(blockMeshDict)

	cd ../faMesh
	rm -f !(faMeshDefinition)
)