#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

cp -r constant/polyMesh_orig constant/polyMesh
cp system/fluid/snappyHexMeshDict system/snappyHexMeshDict
runApplication -l log.blockMesh.fluid blockMesh
runApplication -l log.snappyHexMesh.fluid snappyHexMesh -overwrite
mv -f constant/polyMesh constant/fluid/
runApplication -l log.createpatch.fluid createPatch -region fluid -overwrite

cp -r constant/polyMesh_orig constant/polyMesh
cp system/solid/snappyHexMeshDict system/snappyHexMeshDict
runApplication -l log.blockMesh.solid blockMesh
runApplication -l log.snappyHexMesh.solid snappyHexMesh -overwrite
mv -f constant/polyMesh constant/solid
runApplication -l log.createpatch.solid createPatch -region solid -overwrite

