#!/bin/bash

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

rm -f 0/batteryRegion/T

shopt -s extglob
(
	cd 0/batteryRegion
	rm -f !(orig)
)
(
	cd constant/batteryRegion/polyMesh
	rm -f !(blockMeshDict)

	cd ../faMesh
	rm -f !(faMeshDefinition)
)