#!/bin/sh

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication -l log.recons.fluid reconstructPar -region solid
runApplication -l log.recons.solid reconstructPar -region fluid


